apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: mywebsite
    tier: frontend
spec:
  replicas: 3
  template:
    metadata: ff

---
labels:
app: 
    image: nginx
